/*++
Copyright (c) 2007  Microsoft Corporation

Module Name:
    ndiswwan.h

Abstract:
    Header file for WWAN structures

Revision History:
    DATE			DESCRIPTION
    ------------		-----------
    23-FEB-2007		V0.40 Driver Model Compliant
    23-MAY-2007		V0.50 Driver Model Compliant
    02-APR-2008		V1.00 Driver Model Compliant
--*/

#ifndef __NDIS_WWAN_DECL__
#define __NDIS_WWAN_DECL__

///////////////////////////////////////////////////////////////////////////
//                           wwansvc requests                            //
///////////////////////////////////////////////////////////////////////////

#define NDIS_WWAN_DRIVER_CAPS_REVISION_1		1

typedef struct _NDIS_WWAN_DRIVER_CAPS {
    NDIS_OBJECT_HEADER	Header;
    WWAN_DRIVER_CAPS	DriverCaps;
} NDIS_WWAN_DRIVER_CAPS, *PNDIS_WWAN_DRIVER_CAPS;

#define NDIS_WWAN_SERVICE_ACTIVATION_REVISION_1		1

typedef struct _NDIS_WWAN_SERVICE_ACTIVATION {
    NDIS_OBJECT_HEADER		Header;
    WWAN_SERVICE_ACTIVATION	ServiceActivation;
} NDIS_WWAN_SERVICE_ACTIVATION, *PNDIS_WWAN_SERVICE_ACTIVATION;

#define NDIS_WWAN_SET_RADIO_STATE_REVISION_1		1

typedef struct _NDIS_WWAN_SET_RADIO_STATE {
    NDIS_OBJECT_HEADER	Header;
    WWAN_RADIO		RadioAction;
} NDIS_WWAN_SET_RADIO_STATE, *PNDIS_WWAN_SET_RADIO_STATE;

#define NDIS_WWAN_SET_PIN_REVISION_1			1

typedef struct _NDIS_WWAN_SET_PIN {
    NDIS_OBJECT_HEADER	Header;
    WWAN_PIN_ACTION	PinAction;
} NDIS_WWAN_SET_PIN, *PNDIS_WWAN_SET_PIN;

#define NDIS_WWAN_SET_PREFERRED_PROVIDERS_REVISION_1	1

typedef struct _NDIS_WWAN_SET_PREFERRED_PROVIDERS {
    NDIS_OBJECT_HEADER	Header;
    WWAN_LIST_HEADER	PreferredListHeader;
} NDIS_WWAN_SET_PREFERRED_PROVIDERS, *PNDIS_WWAN_SET_PREFERRED_PROVIDERS;

#define NDIS_WWAN_SET_REGISTER_STATE_REVISION_1		1

typedef struct _NDIS_WWAN_SET_REGISTER_STATE {
    NDIS_OBJECT_HEADER		Header;
    WWAN_SET_REGISTER_STATE	SetRegisterState;
} NDIS_WWAN_SET_REGISTER_STATE, *PNDIS_WWAN_SET_REGISTER_STATE;

#define NDIS_WWAN_SET_SIGNAL_INDICATION_REVISION_1	1

typedef struct _NDIS_WWAN_SET_SIGNAL_INDICATION {
    NDIS_OBJECT_HEADER		Header;
    WWAN_SET_SIGNAL_INDICATION	SignalIndication;
} NDIS_WWAN_SET_SIGNAL_INDICATION, *PNDIS_WWAN_SET_SIGNAL_INDICATION;

#define NDIS_WWAN_SET_PACKET_SERVICE_REVISION_1		1

typedef struct _NDIS_WWAN_SET_PACKET_SERVICE {
    NDIS_OBJECT_HEADER		Header;
    WWAN_PACKET_SERVICE_ACTION	PacketServiceAction;
} NDIS_WWAN_SET_PACKET_SERVICE, *PNDIS_WWAN_SET_PACKET_SERVICE;

#define NDIS_WWAN_SET_PROVISIONED_CONTEXT_REVISION_1	1

typedef struct _NDIS_WWAN_SET_PROVISIONED_CONTEXT {
    NDIS_OBJECT_HEADER	Header;
    WWAN_SET_CONTEXT	ProvisionedContext;
} NDIS_WWAN_SET_PROVISIONED_CONTEXT, *PNDIS_WWAN_SET_PROVISIONED_CONTEXT;

#define NDIS_WWAN_SET_CONTEXT_STATE_REVISION_1		1

typedef struct _NDIS_WWAN_SET_CONTEXT_STATE {
    NDIS_OBJECT_HEADER		Header;
    WWAN_SET_CONTEXT_STATE	SetContextState;
} NDIS_WWAN_SET_CONTEXT_STATE, *PNDIS_WWAN_SET_CONTEXT_STATE;

#define NDIS_WWAN_SET_SMS_CONFIGURATION_REVISION_1	1

typedef struct _NDIS_WWAN_SET_SMS_CONFIGURATION {
    NDIS_OBJECT_HEADER		Header;
    WWAN_SET_SMS_CONFIGURATION	SetSmsConfiguration;
} NDIS_WWAN_SET_SMS_CONFIGURATION, *PNDIS_WWAN_SET_SMS_CONFIGURATION;

#define NDIS_WWAN_SMS_READ_REVISION_1			1

typedef struct _NDIS_WWAN_SMS_READ {
    NDIS_OBJECT_HEADER	Header;
    WWAN_SMS_READ	SmsRead;
} NDIS_WWAN_SMS_READ, *PNDIS_WWAN_SMS_READ;

#define NDIS_WWAN_SMS_SEND_REVISION_1			1

typedef struct _NDIS_WWAN_SMS_SEND {
    NDIS_OBJECT_HEADER	Header;
    WWAN_SMS_SEND	SmsSend;
} NDIS_WWAN_SMS_SEND, *PNDIS_WWAN_SMS_SEND;

#define NDIS_WWAN_SMS_DELETE_REVISION_1			1

typedef struct _NDIS_WWAN_SMS_DELETE {
    NDIS_OBJECT_HEADER	Header;
    WWAN_SMS_FILTER	SmsFilter;
} NDIS_WWAN_SMS_DELETE, *PNDIS_WWAN_SMS_DELETE;

///////////////////////////////////////////////////////////////////////////
//                    device indications and responses                   //
///////////////////////////////////////////////////////////////////////////

#define NDIS_WWAN_DEVICE_CAPS_REVISION_1		1

typedef struct _NDIS_WWAN_DEVICE_CAPS {
    NDIS_OBJECT_HEADER    Header;
    WWAN_STATUS           uStatus;
    WWAN_DEVICE_CAPS      DeviceCaps;
} NDIS_WWAN_DEVICE_CAPS, *PNDIS_WWAN_DEVICE_CAPS;

#define NDIS_WWAN_READY_INFO_REVISION_1			1

typedef struct _NDIS_WWAN_READY_INFO {
    NDIS_OBJECT_HEADER	Header;
    WWAN_READY_INFO	ReadyInfo;
} NDIS_WWAN_READY_INFO, *PNDIS_WWAN_READY_INFO;

#define NDIS_WWAN_SERVICE_ACTIVATION_STATUS_REVISION_1	1

typedef struct _NDIS_WWAN_SERVICE_ACTIVATION_STATUS {
    NDIS_OBJECT_HEADER              Header;
    WWAN_STATUS                     uStatus;
    WWAN_SERVICE_ACTIVATION_STATUS  ServiceActivationStatus;
} NDIS_WWAN_SERVICE_ACTIVATION_STATUS, *PNDIS_WWAN_SERVICE_ACTIVATION_STATUS;

#define NDIS_WWAN_VENDOR_SPECIFIC_REVISION_1   	1

typedef struct _NDIS_WWAN_VENDOR_SPECIFIC {
    NDIS_OBJECT_HEADER        Header;
    WWAN_VENDOR_SPECIFIC      VendorSpecificData;
} NDIS_WWAN_VENDOR_SPECIFIC, *PNDIS_WWAN_VENDOR_SPECIFIC;

#define NDIS_WWAN_RADIO_STATE_REVISION_1		1

typedef struct _NDIS_WWAN_RADIO_STATE {
    NDIS_OBJECT_HEADER	Header;
    WWAN_STATUS		uStatus;
    WWAN_RADIO_STATE	RadioState;
} NDIS_WWAN_RADIO_STATE, *PNDIS_WWAN_RADIO_STATE;

#define NDIS_WWAN_PIN_INFO_REVISION_1			1

typedef struct _NDIS_WWAN_PIN_INFO {
    NDIS_OBJECT_HEADER	Header;
    WWAN_STATUS		uStatus;
    WWAN_PIN_INFO	PinInfo;
} NDIS_WWAN_PIN_INFO, *PNDIS_WWAN_PIN_INFO;

#define NDIS_WWAN_PIN_LIST_REVISION_1			1

typedef struct _NDIS_WWAN_PIN_LIST {
    NDIS_OBJECT_HEADER	Header;
    WWAN_STATUS		uStatus;
    WWAN_PIN_LIST	PinList;
} NDIS_WWAN_PIN_LIST, *PNDIS_WWAN_PIN_LIST;

#define NDIS_WWAN_HOME_PROVIDER_REVISION_1		1

typedef struct _NDIS_WWAN_HOME_PROVIDER {
    NDIS_OBJECT_HEADER	Header;
    WWAN_STATUS		uStatus;
    WWAN_PROVIDER	Provider;
} NDIS_WWAN_HOME_PROVIDER, *PNDIS_WWAN_HOME_PROVIDER;

#define NDIS_WWAN_PREFERRED_PROVIDERS_REVISION_1	1

typedef struct _NDIS_WWAN_PREFERRED_PROVIDERS {
    NDIS_OBJECT_HEADER	Header;
    WWAN_STATUS		uStatus;
    WWAN_LIST_HEADER	PreferredListHeader;
} NDIS_WWAN_PREFERRED_PROVIDERS, *PNDIS_WWAN_PREFERRED_PROVIDERS;

#define NDIS_WWAN_VISIBLE_PROVIDERS_REVISION_1		1

typedef struct _NDIS_WWAN_VISIBLE_PROVIDERS {
    NDIS_OBJECT_HEADER	Header;
    WWAN_STATUS		uStatus;
    WWAN_LIST_HEADER	VisibleListHeader;
} NDIS_WWAN_VISIBLE_PROVIDERS, *PNDIS_WWAN_VISIBLE_PROVIDERS;

#define NDIS_WWAN_REGISTRATION_STATE_REVISION_1		1

typedef struct _NDIS_WWAN_REGISTRATION_STATE {
    NDIS_OBJECT_HEADER		Header;
    WWAN_STATUS			uStatus;
    WWAN_REGISTRATION_STATE	RegistrationState;
} NDIS_WWAN_REGISTRATION_STATE, *PNDIS_WWAN_REGISTRATION_STATE;

#define NDIS_WWAN_SIGNAL_STATE_REVISION_1		1

typedef struct _NDIS_WWAN_SIGNAL_STATE {
    NDIS_OBJECT_HEADER	Header;
    WWAN_STATUS		uStatus;
    WWAN_SIGNAL_STATE	SignalState;
} NDIS_WWAN_SIGNAL_STATE, *PNDIS_WWAN_SIGNAL_STATE;

#define NDIS_WWAN_PACKET_SERVICE_STATE_REVISION_1	1

typedef struct _NDIS_WWAN_PACKET_SERVICE_STATE {
    NDIS_OBJECT_HEADER	Header;
    WWAN_STATUS		uStatus;
    WWAN_PACKET_SERVICE	PacketService;
} NDIS_WWAN_PACKET_SERVICE_STATE, *PNDIS_WWAN_PACKET_SERVICE_STATE;

#define NDIS_WWAN_CONTEXT_STATE_REVISION_1		1

typedef struct _NDIS_WWAN_CONTEXT_STATE {
    NDIS_OBJECT_HEADER	Header;
    WWAN_STATUS		uStatus;
    WWAN_CONTEXT_STATE	ContextState;
} NDIS_WWAN_CONTEXT_STATE, *PNDIS_WWAN_CONTEXT_STATE;

#define NDIS_WWAN_PROVISIONED_CONTEXTS_REVISION_1	1

typedef struct _NDIS_WWAN_PROVISIONED_CONTEXTS {
    NDIS_OBJECT_HEADER	Header;
    WWAN_STATUS		uStatus;
    WWAN_LIST_HEADER	ContextListHeader;
} NDIS_WWAN_PROVISIONED_CONTEXTS, *PNDIS_WWAN_PROVISIONED_CONTEXTS;

#define NDIS_WWAN_SMS_CONFIGURATION_REVISION_1		1

typedef struct _NDIS_WWAN_SMS_CONFIGURATION {
    NDIS_OBJECT_HEADER		Header;
    WWAN_STATUS			uStatus;
    WWAN_SMS_CONFIGURATION	SmsConfiguration;
} NDIS_WWAN_SMS_CONFIGURATION, *PNDIS_WWAN_SMS_CONFIGURATION;

#define NDIS_WWAN_SMS_RECEIVE_REVISION_1		1

typedef struct _NDIS_WWAN_SMS_RECEIVE {
    NDIS_OBJECT_HEADER	Header;
    WWAN_STATUS		uStatus;
    WWAN_LIST_HEADER	SmsListHeader;
} NDIS_WWAN_SMS_RECEIVE, *PNDIS_WWAN_SMS_RECEIVE;

#define NDIS_WWAN_SMS_SEND_STATUS_REVISION_1		1

typedef struct _NDIS_WWAN_SMS_SEND_STATUS {
    NDIS_OBJECT_HEADER	Header;
    WWAN_STATUS		uStatus;
    ULONG		MessageReference;
} NDIS_WWAN_SMS_SEND_STATUS, *PNDIS_WWAN_SMS_SEND_STATUS;

#define NDIS_WWAN_SMS_DELETE_STATUS_REVISION_1		1

typedef struct _NDIS_WWAN_SMS_DELETE_STATUS {
    NDIS_OBJECT_HEADER	Header;
    WWAN_STATUS		uStatus;
} NDIS_WWAN_SMS_DELETE_STATUS, *PNDIS_WWAN_SMS_DELETE_STATUS;

#define NDIS_WWAN_SMS_STATUS_REVISION_1			1

typedef struct _NDIS_WWAN_SMS_STATUS {
    NDIS_OBJECT_HEADER	Header;
    WWAN_STATUS		uStatus;
    WWAN_SMS_STATUS	SmsStatus;
} NDIS_WWAN_SMS_STATUS, *PNDIS_WWAN_SMS_STATUS;

#endif

