/*
	Copyright (c) Microsoft Corporation.  All rights reserved.
*/

#if defined(fun_WDF_USB_READERS_FAILED_1) || \
	defined(fun_WDF_USB_READERS_FAILED_2) || \
	defined(fun_WDF_USB_READERS_FAILED_3) ||\
	defined(fun_WDF_USB_READER_COMPLETION_ROUTINE_1) || \
	defined(fun_WDF_USB_READER_COMPLETION_ROUTINE_2) || \
	defined(fun_WDF_USB_READER_COMPLETION_ROUTINE_3) 
  #define SDV_USB_SUPPORT 1
#endif

#if defined(SDV_USB_SUPPORT)
    #include "usbdi.h"
    #include "usbdlib.h"
#endif
#include <wdf.h>
#if defined(SDV_USB_SUPPORT)
    #include <wdfusb.h>
#endif


extern DRIVER_INITIALIZE fun_DriverEntry;

#ifdef fun_WDF_DEVICE_CONTEXT_CLEANUP
extern EVT_WDF_DEVICE_CONTEXT_CLEANUP fun_WDF_DEVICE_CONTEXT_CLEANUP; 
#endif
#ifdef fun_WDF_DEVICE_CONTEXT_DESTROY
extern EVT_WDF_DEVICE_CONTEXT_DESTROY fun_WDF_DEVICE_CONTEXT_DESTROY; 
#endif
#ifdef fun_WDF_IO_QUEUE_CONTEXT_CLEANUP_CALLBACK
extern EVT_WDF_IO_QUEUE_CONTEXT_CLEANUP_CALLBACK fun_WDF_IO_QUEUE_CONTEXT_CLEANUP_CALLBACK; 
#endif
#ifdef fun_WDF_IO_QUEUE_CONTEXT_DESTROY_CALLBACK
extern EVT_WDF_IO_QUEUE_CONTEXT_DESTROY_CALLBACK fun_WDF_IO_QUEUE_CONTEXT_DESTROY_CALLBACK; 
#endif
#ifdef fun_WDF_FILE_CONTEXT_CLEANUP_CALLBACK
extern EVT_WDF_FILE_CONTEXT_CLEANUP_CALLBACK fun_WDF_FILE_CONTEXT_CLEANUP_CALLBACK; 
#endif
#ifdef fun_WDF_FILE_CONTEXT_DESTROY_CALLBACK
extern EVT_WDF_FILE_CONTEXT_DESTROY_CALLBACK fun_WDF_FILE_CONTEXT_DESTROY_CALLBACK; 
#endif
#ifdef fun_WDF_CHILD_LIST_CREATE_DEVICE
extern EVT_WDF_CHILD_LIST_CREATE_DEVICE fun_WDF_CHILD_LIST_CREATE_DEVICE; 
#endif
#ifdef fun_WDF_CHILD_LIST_SCAN_FOR_CHILDREN
extern EVT_WDF_CHILD_LIST_SCAN_FOR_CHILDREN fun_WDF_CHILD_LIST_SCAN_FOR_CHILDREN; 
#endif
#ifdef fun_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_COPY
extern EVT_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_COPY fun_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_COPY; 
#endif
#ifdef fun_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_DUPLICATE
extern EVT_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_DUPLICATE fun_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_DUPLICATE; 
#endif
#ifdef fun_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_COMPARE
extern EVT_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_COMPARE fun_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_COMPARE; 
#endif
#ifdef fun_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_CLEANUP
extern EVT_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_CLEANUP fun_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_CLEANUP; 
#endif
#ifdef fun_WDF_CHILD_LIST_ADDRESS_DESCRIPTION_COPY
extern EVT_WDF_CHILD_LIST_ADDRESS_DESCRIPTION_COPY fun_WDF_CHILD_LIST_ADDRESS_DESCRIPTION_COPY; 
#endif
#ifdef fun_WDF_CHILD_LIST_ADDRESS_DESCRIPTION_DUPLICATE
extern EVT_WDF_CHILD_LIST_ADDRESS_DESCRIPTION_DUPLICATE fun_WDF_CHILD_LIST_ADDRESS_DESCRIPTION_DUPLICATE; 
#endif
#ifdef fun_WDF_CHILD_LIST_ADDRESS_DESCRIPTION_CLEANUP
extern EVT_WDF_CHILD_LIST_ADDRESS_DESCRIPTION_CLEANUP fun_WDF_CHILD_LIST_ADDRESS_DESCRIPTION_CLEANUP; 
#endif
#ifdef fun_WDF_CHILD_LIST_DEVICE_REENUMERATED
extern EVT_WDF_CHILD_LIST_DEVICE_REENUMERATED fun_WDF_CHILD_LIST_DEVICE_REENUMERATED; 
#endif
#ifdef fun_WDF_CLASS_EXTENSIONIN_BIND
extern EVT_WDF_CLASS_EXTENSIONIN_BIND fun_WDF_CLASS_EXTENSIONIN_BIND; 
#endif
#ifdef fun_WDF_CLASS_EXTENSIONIN_UNBIND
extern EVT_WDF_CLASS_EXTENSIONIN_UNBIND fun_WDF_CLASS_EXTENSIONIN_UNBIND; 
#endif
#ifdef fun_WDF_DEVICE_SHUTDOWN_NOTIFICATION
extern EVT_WDF_DEVICE_SHUTDOWN_NOTIFICATION fun_WDF_DEVICE_SHUTDOWN_NOTIFICATION; 
#endif
#ifdef fun_WDF_DEVICE_FILE_CREATE
extern EVT_WDF_DEVICE_FILE_CREATE fun_WDF_DEVICE_FILE_CREATE; 
#endif
#ifdef fun_WDF_FILE_CLOSE
extern EVT_WDF_FILE_CLOSE fun_WDF_FILE_CLOSE; 
#endif
#ifdef fun_WDF_FILE_CLEANUP
extern EVT_WDF_FILE_CLEANUP fun_WDF_FILE_CLEANUP; 
#endif
#ifdef fun_WDF_DEVICE_PNP_STATE_CHANGE_NOTIFICATION
extern EVT_WDF_DEVICE_PNP_STATE_CHANGE_NOTIFICATION fun_WDF_DEVICE_PNP_STATE_CHANGE_NOTIFICATION; 
#endif
#ifdef fun_WDF_DEVICE_POWER_STATE_CHANGE_NOTIFICATION
extern EVT_WDF_DEVICE_POWER_STATE_CHANGE_NOTIFICATION fun_WDF_DEVICE_POWER_STATE_CHANGE_NOTIFICATION; 
#endif
#ifdef fun_WDF_DEVICE_POWER_POLICY_STATE_CHANGE_NOTIFICATION
extern EVT_WDF_DEVICE_POWER_POLICY_STATE_CHANGE_NOTIFICATION fun_WDF_DEVICE_POWER_POLICY_STATE_CHANGE_NOTIFICATION; 
#endif
#ifdef fun_WDF_DEVICE_D0_ENTRY
extern EVT_WDF_DEVICE_D0_ENTRY fun_WDF_DEVICE_D0_ENTRY; 
#endif
#ifdef fun_WDF_DEVICE_D0_ENTRY_POST_INTERRUPTS_ENABLED
extern EVT_WDF_DEVICE_D0_ENTRY_POST_INTERRUPTS_ENABLED fun_WDF_DEVICE_D0_ENTRY_POST_INTERRUPTS_ENABLED; 
#endif
#ifdef fun_WDF_DEVICE_D0_EXIT
extern EVT_WDF_DEVICE_D0_EXIT fun_WDF_DEVICE_D0_EXIT; 
#endif
#ifdef fun_WDF_DEVICE_D0_EXIT_PRE_INTERRUPTS_DISABLED
extern EVT_WDF_DEVICE_D0_EXIT_PRE_INTERRUPTS_DISABLED fun_WDF_DEVICE_D0_EXIT_PRE_INTERRUPTS_DISABLED; 
#endif
#ifdef fun_WDF_DEVICE_PREPARE_HARDWARE
extern EVT_WDF_DEVICE_PREPARE_HARDWARE fun_WDF_DEVICE_PREPARE_HARDWARE; 
#endif
#ifdef fun_WDF_DEVICE_RELEASE_HARDWARE
extern EVT_WDF_DEVICE_RELEASE_HARDWARE fun_WDF_DEVICE_RELEASE_HARDWARE; 
#endif
#ifdef fun_WDF_DEVICE_SELF_MANAGED_IO_CLEANUP
extern EVT_WDF_DEVICE_SELF_MANAGED_IO_CLEANUP fun_WDF_DEVICE_SELF_MANAGED_IO_CLEANUP; 
#endif
#ifdef fun_WDF_DEVICE_SELF_MANAGED_IO_FLUSH
extern EVT_WDF_DEVICE_SELF_MANAGED_IO_FLUSH fun_WDF_DEVICE_SELF_MANAGED_IO_FLUSH; 
#endif
#ifdef fun_WDF_DEVICE_SELF_MANAGED_IO_INIT
extern EVT_WDF_DEVICE_SELF_MANAGED_IO_INIT fun_WDF_DEVICE_SELF_MANAGED_IO_INIT; 
#endif
#ifdef fun_WDF_DEVICE_SELF_MANAGED_IO_SUSPEND
extern EVT_WDF_DEVICE_SELF_MANAGED_IO_SUSPEND fun_WDF_DEVICE_SELF_MANAGED_IO_SUSPEND; 
#endif
#ifdef fun_WDF_DEVICE_SELF_MANAGED_IO_RESTART
extern EVT_WDF_DEVICE_SELF_MANAGED_IO_RESTART fun_WDF_DEVICE_SELF_MANAGED_IO_RESTART; 
#endif
#ifdef fun_WDF_DEVICE_QUERY_STOP
extern EVT_WDF_DEVICE_QUERY_STOP fun_WDF_DEVICE_QUERY_STOP; 
#endif
#ifdef fun_WDF_DEVICE_QUERY_REMOVE
extern EVT_WDF_DEVICE_QUERY_REMOVE fun_WDF_DEVICE_QUERY_REMOVE; 
#endif
#ifdef fun_WDF_DEVICE_SURPRISE_REMOVAL
extern EVT_WDF_DEVICE_SURPRISE_REMOVAL fun_WDF_DEVICE_SURPRISE_REMOVAL; 
#endif
#ifdef fun_WDF_DEVICE_USAGE_NOTIFICATION
extern EVT_WDF_DEVICE_USAGE_NOTIFICATION fun_WDF_DEVICE_USAGE_NOTIFICATION; 
#endif
#ifdef fun_WDF_DEVICE_RELATIONS_QUERY
extern EVT_WDF_DEVICE_RELATIONS_QUERY fun_WDF_DEVICE_RELATIONS_QUERY; 
#endif
#ifdef fun_WDF_DEVICE_ARM_WAKE_FROM_S0
extern EVT_WDF_DEVICE_ARM_WAKE_FROM_S0 fun_WDF_DEVICE_ARM_WAKE_FROM_S0; 
#endif
#ifdef fun_WDF_DEVICE_ARM_WAKE_FROM_SX
extern EVT_WDF_DEVICE_ARM_WAKE_FROM_SX fun_WDF_DEVICE_ARM_WAKE_FROM_SX; 
#endif
#ifdef fun_WDF_DEVICE_DISARM_WAKE_FROM_S0
extern EVT_WDF_DEVICE_DISARM_WAKE_FROM_S0 fun_WDF_DEVICE_DISARM_WAKE_FROM_S0; 
#endif
#ifdef fun_WDF_DEVICE_DISARM_WAKE_FROM_SX
extern EVT_WDF_DEVICE_DISARM_WAKE_FROM_SX fun_WDF_DEVICE_DISARM_WAKE_FROM_SX; 
#endif
#ifdef fun_WDF_DEVICE_WAKE_FROM_S0_TRIGGERED
extern EVT_WDF_DEVICE_WAKE_FROM_S0_TRIGGERED fun_WDF_DEVICE_WAKE_FROM_S0_TRIGGERED; 
#endif
#ifdef fun_WDF_DEVICE_WAKE_FROM_SX_TRIGGERED
extern EVT_WDF_DEVICE_WAKE_FROM_SX_TRIGGERED fun_WDF_DEVICE_WAKE_FROM_SX_TRIGGERED; 
#endif
#ifdef fun_WDFDEVICE_WDM_IRP_PREPROCESS_1
extern EVT_WDFDEVICE_WDM_IRP_PREPROCESS fun_WDFDEVICE_WDM_IRP_PREPROCESS_1; /*multiple*/
#endif

#ifdef fun_WDFDEVICE_WDM_IRP_PREPROCESS_2
extern EVT_WDFDEVICE_WDM_IRP_PREPROCESS fun_WDFDEVICE_WDM_IRP_PREPROCESS_2; /*multiple*/
#endif

#ifdef fun_WDFDEVICE_WDM_IRP_PREPROCESS_3
extern EVT_WDFDEVICE_WDM_IRP_PREPROCESS fun_WDFDEVICE_WDM_IRP_PREPROCESS_3; /*multiple*/
#endif

#ifdef fun_WDFDEVICE_WDM_IRP_PREPROCESS_4
extern EVT_WDFDEVICE_WDM_IRP_PREPROCESS fun_WDFDEVICE_WDM_IRP_PREPROCESS_4; /*multiple*/
#endif

#ifdef fun_WDFDEVICE_WDM_IRP_PREPROCESS_5
extern EVT_WDFDEVICE_WDM_IRP_PREPROCESS fun_WDFDEVICE_WDM_IRP_PREPROCESS_5; /*multiple*/
#endif

#ifdef fun_WDFDEVICE_WDM_IRP_PREPROCESS_6
extern EVT_WDFDEVICE_WDM_IRP_PREPROCESS fun_WDFDEVICE_WDM_IRP_PREPROCESS_6; /*multiple*/
#endif

#ifdef fun_WDF_IO_IN_CALLER_CONTEXT
extern EVT_WDF_IO_IN_CALLER_CONTEXT fun_WDF_IO_IN_CALLER_CONTEXT; 
#endif
#ifdef fun_WDF_DMA_ENABLER_FILL
extern EVT_WDF_DMA_ENABLER_FILL fun_WDF_DMA_ENABLER_FILL; 
#endif
#ifdef fun_WDF_DMA_ENABLER_FLUSH
extern EVT_WDF_DMA_ENABLER_FLUSH fun_WDF_DMA_ENABLER_FLUSH; 
#endif
#ifdef fun_WDF_DMA_ENABLER_ENABLE
extern EVT_WDF_DMA_ENABLER_ENABLE fun_WDF_DMA_ENABLER_ENABLE; 
#endif
#ifdef fun_WDF_DMA_ENABLER_DISABLE
extern EVT_WDF_DMA_ENABLER_DISABLE fun_WDF_DMA_ENABLER_DISABLE; 
#endif
#ifdef fun_WDF_DMA_ENABLER_SELFMANAGED_IO_START
extern EVT_WDF_DMA_ENABLER_SELFMANAGED_IO_START fun_WDF_DMA_ENABLER_SELFMANAGED_IO_START; 
#endif
#ifdef fun_WDF_DMA_ENABLER_SELFMANAGED_IO_STOP
extern EVT_WDF_DMA_ENABLER_SELFMANAGED_IO_STOP fun_WDF_DMA_ENABLER_SELFMANAGED_IO_STOP; 
#endif
#ifdef fun_WDF_PROGRAM_DMA_1
extern EVT_WDF_PROGRAM_DMA fun_WDF_PROGRAM_DMA_1; /*multiple*/
#endif
#ifdef fun_WDF_PROGRAM_DMA_2
extern EVT_WDF_PROGRAM_DMA fun_WDF_PROGRAM_DMA_2; /*multiple*/
#endif
#ifdef fun_WDF_PROGRAM_DMA_3
extern EVT_WDF_PROGRAM_DMA fun_WDF_PROGRAM_DMA_3; /*multiple*/
#endif
#ifdef fun_WDF_PROGRAM_DMA_4
extern EVT_WDF_PROGRAM_DMA fun_WDF_PROGRAM_DMA_4; /*multiple*/
#endif
#ifdef fun_WDF_PROGRAM_DMA_5
extern EVT_WDF_PROGRAM_DMA fun_WDF_PROGRAM_DMA_5; /*multiple*/
#endif
#ifdef fun_WDF_PROGRAM_DMA_6
extern EVT_WDF_PROGRAM_DMA fun_WDF_PROGRAM_DMA_6; /*multiple*/
#endif
#ifdef fun_WDF_DPC_1
extern EVT_WDF_DPC fun_WDF_DPC_1; /*multiple*/
#endif
#ifdef fun_WDF_DPC_2
extern EVT_WDF_DPC fun_WDF_DPC_2; /*multiple*/
#endif
#ifdef fun_WDF_DPC_3
extern EVT_WDF_DPC fun_WDF_DPC_3; /*multiple*/
#endif
#ifdef fun_WDF_DPC_4
extern EVT_WDF_DPC fun_WDF_DPC_4; /*multiple*/
#endif
#ifdef fun_WDF_DPC_5
extern EVT_WDF_DPC fun_WDF_DPC_5; /*multiple*/
#endif
#ifdef fun_WDF_DPC_6
extern EVT_WDF_DPC fun_WDF_DPC_6; /*multiple*/
#endif
#ifdef fun_WDF_DPC_7
extern EVT_WDF_DPC fun_WDF_DPC_7; /*multiple*/
#endif
#ifdef fun_WDF_DRIVER_DEVICE_ADD
extern EVT_WDF_DRIVER_DEVICE_ADD fun_WDF_DRIVER_DEVICE_ADD; 
#endif
#ifdef fun_WDF_DRIVER_UNLOAD
extern EVT_WDF_DRIVER_UNLOAD fun_WDF_DRIVER_UNLOAD; 
#endif
#ifdef fun_WDF_TRACE_CALLBACK
extern EVT_WDF_TRACE_CALLBACK fun_WDF_TRACE_CALLBACK; 
#endif
#ifdef fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_1
extern EVT_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_1; /*multiple*/
#endif
#ifdef fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_2
extern EVT_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_2; /*multiple*/
#endif
#ifdef fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_3
extern EVT_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_3; /*multiple*/
#endif
#ifdef fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_4
extern EVT_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_4; /*multiple*/
#endif
#ifdef fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_5
extern EVT_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_5; /*multiple*/
#endif
#ifdef fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_6
extern EVT_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_6; /*multiple*/
#endif
#ifdef fun_WDF_DEVICE_REMOVE_ADDED_RESOURCES
extern EVT_WDF_DEVICE_REMOVE_ADDED_RESOURCES fun_WDF_DEVICE_REMOVE_ADDED_RESOURCES; 
#endif
#ifdef fun_WDF_INTERRUPT_ISR
extern EVT_WDF_INTERRUPT_ISR fun_WDF_INTERRUPT_ISR; 
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_1
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_1; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_2
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_2; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_3
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_3; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_4
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_4; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_5
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_5; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_6
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_6; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_7
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_7; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_8
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_8; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_9
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_9; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_10
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_10; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_11
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_11; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_DPC
extern EVT_WDF_INTERRUPT_DPC fun_WDF_INTERRUPT_DPC; 
#endif
#ifdef fun_WDF_INTERRUPT_ENABLE
extern EVT_WDF_INTERRUPT_ENABLE fun_WDF_INTERRUPT_ENABLE; 
#endif
#ifdef fun_WDF_INTERRUPT_DISABLE
extern EVT_WDF_INTERRUPT_DISABLE fun_WDF_INTERRUPT_DISABLE; 
#endif
#ifdef fun_WDF_IO_QUEUE_IO_DEFAULT
extern EVT_WDF_IO_QUEUE_IO_DEFAULT fun_WDF_IO_QUEUE_IO_DEFAULT; 
#endif
#ifdef fun_WDF_IO_QUEUE_IO_STOP
extern EVT_WDF_IO_QUEUE_IO_STOP fun_WDF_IO_QUEUE_IO_STOP; 
#endif
#ifdef fun_WDF_IO_QUEUE_IO_RESUME
extern EVT_WDF_IO_QUEUE_IO_RESUME fun_WDF_IO_QUEUE_IO_RESUME; 
#endif
#ifdef fun_WDF_IO_QUEUE_IO_READ
extern EVT_WDF_IO_QUEUE_IO_READ fun_WDF_IO_QUEUE_IO_READ; 
#endif
#ifdef fun_WDF_IO_QUEUE_IO_WRITE
extern EVT_WDF_IO_QUEUE_IO_WRITE fun_WDF_IO_QUEUE_IO_WRITE; 
#endif
#ifdef fun_WDF_IO_QUEUE_IO_DEVICE_CONTROL
extern EVT_WDF_IO_QUEUE_IO_DEVICE_CONTROL fun_WDF_IO_QUEUE_IO_DEVICE_CONTROL; 
#endif
#ifdef fun_WDF_IO_QUEUE_IO_INTERNAL_DEVICE_CONTROL
extern EVT_WDF_IO_QUEUE_IO_INTERNAL_DEVICE_CONTROL fun_WDF_IO_QUEUE_IO_INTERNAL_DEVICE_CONTROL; 
#endif
#ifdef fun_WDF_IO_QUEUE_IO_CANCELED_ON_QUEUE
extern EVT_WDF_IO_QUEUE_IO_CANCELED_ON_QUEUE fun_WDF_IO_QUEUE_IO_CANCELED_ON_QUEUE; 
#endif
#ifdef fun_SDV_WDF_IO_QUEUE_STATE
extern EVT_WDF_IO_QUEUE_STATE fun_SDV_WDF_IO_QUEUE_STATE; 
#endif
#ifdef fun_WDF_IO_TARGET_QUERY_REMOVE
extern EVT_WDF_IO_TARGET_QUERY_REMOVE fun_WDF_IO_TARGET_QUERY_REMOVE; 
#endif
#ifdef fun_WDF_IO_TARGET_REMOVE_CANCELED
extern EVT_WDF_IO_TARGET_REMOVE_CANCELED fun_WDF_IO_TARGET_REMOVE_CANCELED; 
#endif
#ifdef fun_WDF_IO_TARGET_REMOVE_COMPLETE
extern EVT_WDF_IO_TARGET_REMOVE_COMPLETE fun_WDF_IO_TARGET_REMOVE_COMPLETE; 
#endif
#ifdef fun_WDF_OBJECT_CONTEXT_CLEANUP
extern EVT_WDF_OBJECT_CONTEXT_CLEANUP fun_WDF_OBJECT_CONTEXT_CLEANUP; 
#endif
#ifdef fun_WDF_OBJECT_CONTEXT_DESTROY
extern EVT_WDF_OBJECT_CONTEXT_DESTROY fun_WDF_OBJECT_CONTEXT_DESTROY; 
#endif
#ifdef fun_WDF_DEVICE_RESOURCES_QUERY
extern EVT_WDF_DEVICE_RESOURCES_QUERY fun_WDF_DEVICE_RESOURCES_QUERY; 
#endif
#ifdef fun_WDF_DEVICE_RESOURCE_REQUIREMENTS_QUERY
extern EVT_WDF_DEVICE_RESOURCE_REQUIREMENTS_QUERY fun_WDF_DEVICE_RESOURCE_REQUIREMENTS_QUERY; 
#endif
#ifdef fun_WDF_DEVICE_EJECT
extern EVT_WDF_DEVICE_EJECT fun_WDF_DEVICE_EJECT; 
#endif
#ifdef fun_WDF_DEVICE_SET_LOCK
extern EVT_WDF_DEVICE_SET_LOCK fun_WDF_DEVICE_SET_LOCK; 
#endif
#ifdef fun_WDF_DEVICE_ENABLE_WAKE_AT_BUS
extern EVT_WDF_DEVICE_ENABLE_WAKE_AT_BUS fun_WDF_DEVICE_ENABLE_WAKE_AT_BUS; 
#endif
#ifdef fun_WDF_DEVICE_DISABLE_WAKE_AT_BUS
extern EVT_WDF_DEVICE_DISABLE_WAKE_AT_BUS fun_WDF_DEVICE_DISABLE_WAKE_AT_BUS; 
#endif
#ifdef fun_WDF_DEVICE_PROCESS_QUERY_INTERFACE_REQUEST
extern EVT_WDF_DEVICE_PROCESS_QUERY_INTERFACE_REQUEST fun_WDF_DEVICE_PROCESS_QUERY_INTERFACE_REQUEST; 
#endif
#ifdef fun_WDF_REQUEST_CANCEL_1
extern EVT_WDF_REQUEST_CANCEL fun_WDF_REQUEST_CANCEL_1; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_CANCEL_2
extern EVT_WDF_REQUEST_CANCEL fun_WDF_REQUEST_CANCEL_2; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_CANCEL_3
extern EVT_WDF_REQUEST_CANCEL fun_WDF_REQUEST_CANCEL_3; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_CANCEL_4
extern EVT_WDF_REQUEST_CANCEL fun_WDF_REQUEST_CANCEL_4; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_CANCEL_5
extern EVT_WDF_REQUEST_CANCEL fun_WDF_REQUEST_CANCEL_5; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_CANCEL_6
extern EVT_WDF_REQUEST_CANCEL fun_WDF_REQUEST_CANCEL_6; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_COMPLETION_ROUTINE_1
extern EVT_WDF_REQUEST_COMPLETION_ROUTINE fun_WDF_REQUEST_COMPLETION_ROUTINE_1; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_COMPLETION_ROUTINE_2
extern EVT_WDF_REQUEST_COMPLETION_ROUTINE fun_WDF_REQUEST_COMPLETION_ROUTINE_2; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_COMPLETION_ROUTINE_3
extern EVT_WDF_REQUEST_COMPLETION_ROUTINE fun_WDF_REQUEST_COMPLETION_ROUTINE_3; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_COMPLETION_ROUTINE_4
extern EVT_WDF_REQUEST_COMPLETION_ROUTINE fun_WDF_REQUEST_COMPLETION_ROUTINE_4; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_COMPLETION_ROUTINE_5
extern EVT_WDF_REQUEST_COMPLETION_ROUTINE fun_WDF_REQUEST_COMPLETION_ROUTINE_5; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_COMPLETION_ROUTINE_6
extern EVT_WDF_REQUEST_COMPLETION_ROUTINE fun_WDF_REQUEST_COMPLETION_ROUTINE_6; /*multiple*/
#endif
#ifdef fun_WDF_TIMER_1
extern EVT_WDF_TIMER fun_WDF_TIMER_1; /*multiple*/
#endif
#ifdef fun_WDF_TIMER_2
extern EVT_WDF_TIMER fun_WDF_TIMER_2; /*multiple*/
#endif
#ifdef fun_WDF_TIMER_3
extern EVT_WDF_TIMER fun_WDF_TIMER_3; /*multiple*/
#endif
#ifdef fun_WDF_TIMER_4
extern EVT_WDF_TIMER fun_WDF_TIMER_4; /*multiple*/
#endif
#ifdef fun_WDF_TIMER_5
extern EVT_WDF_TIMER fun_WDF_TIMER_5; /*multiple*/
#endif
#ifdef fun_WDF_TIMER_6
extern EVT_WDF_TIMER fun_WDF_TIMER_6; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_1
extern EVT_WDF_WMI_INSTANCE_QUERY_INSTANCE fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_1; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_2
extern EVT_WDF_WMI_INSTANCE_QUERY_INSTANCE fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_2; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_3
extern EVT_WDF_WMI_INSTANCE_QUERY_INSTANCE fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_3; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_4
extern EVT_WDF_WMI_INSTANCE_QUERY_INSTANCE fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_4; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_5
extern EVT_WDF_WMI_INSTANCE_QUERY_INSTANCE fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_5; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_SET_INSTANCE_1
extern EVT_WDF_WMI_INSTANCE_SET_INSTANCE fun_WDF_WMI_INSTANCE_SET_INSTANCE_1; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_SET_INSTANCE_2
extern EVT_WDF_WMI_INSTANCE_SET_INSTANCE fun_WDF_WMI_INSTANCE_SET_INSTANCE_2; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_SET_INSTANCE_3
extern EVT_WDF_WMI_INSTANCE_SET_INSTANCE fun_WDF_WMI_INSTANCE_SET_INSTANCE_3; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_SET_INSTANCE_4
extern EVT_WDF_WMI_INSTANCE_SET_INSTANCE fun_WDF_WMI_INSTANCE_SET_INSTANCE_4; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_SET_INSTANCE_5
extern EVT_WDF_WMI_INSTANCE_SET_INSTANCE fun_WDF_WMI_INSTANCE_SET_INSTANCE_5; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_SET_ITEM_1
extern EVT_WDF_WMI_INSTANCE_SET_ITEM fun_WDF_WMI_INSTANCE_SET_ITEM_1; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_SET_ITEM_2
extern EVT_WDF_WMI_INSTANCE_SET_ITEM fun_WDF_WMI_INSTANCE_SET_ITEM_2; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_SET_ITEM_3
extern EVT_WDF_WMI_INSTANCE_SET_ITEM fun_WDF_WMI_INSTANCE_SET_ITEM_3; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_SET_ITEM_4
extern EVT_WDF_WMI_INSTANCE_SET_ITEM fun_WDF_WMI_INSTANCE_SET_ITEM_4; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_SET_ITEM_5
extern EVT_WDF_WMI_INSTANCE_SET_ITEM fun_WDF_WMI_INSTANCE_SET_ITEM_5; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_EXECUTE_METHOD_1
extern EVT_WDF_WMI_INSTANCE_EXECUTE_METHOD fun_WDF_WMI_INSTANCE_EXECUTE_METHOD_1; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_EXECUTE_METHOD_2
extern EVT_WDF_WMI_INSTANCE_EXECUTE_METHOD fun_WDF_WMI_INSTANCE_EXECUTE_METHOD_2; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_EXECUTE_METHOD_3
extern EVT_WDF_WMI_INSTANCE_EXECUTE_METHOD fun_WDF_WMI_INSTANCE_EXECUTE_METHOD_3; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_EXECUTE_METHOD_4
extern EVT_WDF_WMI_INSTANCE_EXECUTE_METHOD fun_WDF_WMI_INSTANCE_EXECUTE_METHOD_4; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_EXECUTE_METHOD_5
extern EVT_WDF_WMI_INSTANCE_EXECUTE_METHOD fun_WDF_WMI_INSTANCE_EXECUTE_METHOD_5; /*multiple*/
#endif
#ifdef fun_WDF_WMI_PROVIDER_FUNCTION_CONTROL
extern EVT_WDF_WMI_PROVIDER_FUNCTION_CONTROL fun_WDF_WMI_PROVIDER_FUNCTION_CONTROL; 
#endif
#ifdef fun_WDF_WORKITEM_1
extern EVT_WDF_WORKITEM fun_WDF_WORKITEM_1; /*multiple*/
#endif
#ifdef fun_WDF_WORKITEM_2
extern EVT_WDF_WORKITEM fun_WDF_WORKITEM_2; /*multiple*/
#endif
#ifdef fun_WDF_WORKITEM_3
extern EVT_WDF_WORKITEM fun_WDF_WORKITEM_3; /*multiple*/
#endif
#ifdef fun_WDF_WORKITEM_4
extern EVT_WDF_WORKITEM fun_WDF_WORKITEM_4; /*multiple*/
#endif
#ifdef fun_WDF_WORKITEM_5
extern EVT_WDF_WORKITEM fun_WDF_WORKITEM_5; /*multiple*/
#endif
#ifdef fun_WDF_WORKITEM_6
extern EVT_WDF_WORKITEM fun_WDF_WORKITEM_6; /*multiple*/
#endif
#ifdef fun_WDF_USB_READERS_FAILED_1
extern EVT_WDF_USB_READERS_FAILED fun_WDF_USB_READERS_FAILED_1; /*multiple*/ 
#endif
#ifdef fun_WDF_USB_READERS_FAILED_2
extern EVT_WDF_USB_READERS_FAILED fun_WDF_USB_READERS_FAILED_2; /*multiple*/ 
#endif
#ifdef fun_WDF_USB_READERS_FAILED_3
extern EVT_WDF_USB_READERS_FAILED fun_WDF_USB_READERS_FAILED_3; /*multiple*/ 
#endif
#ifdef fun_WDF_USB_READER_COMPLETION_ROUTINE_1
extern EVT_WDF_USB_READER_COMPLETION_ROUTINE fun_WDF_USB_READER_COMPLETION_ROUTINE_1; /*multiple*/  
#endif
#ifdef fun_WDF_USB_READER_COMPLETION_ROUTINE_2
extern EVT_WDF_USB_READER_COMPLETION_ROUTINE fun_WDF_USB_READER_COMPLETION_ROUTINE_2; /*multiple*/  
#endif
#ifdef fun_WDF_USB_READER_COMPLETION_ROUTINE_3
extern EVT_WDF_USB_READER_COMPLETION_ROUTINE fun_WDF_USB_READER_COMPLETION_ROUTINE_3; /*multiple*/  
#endif

