/*
 Copyright (c) Microsoft Corporation.  All rights reserved.
*/


/*define fun_WDF_DEVICE_WAKE_FROM_SX_TRIGGERED core_callback
define fun_WDF_DEVICE_D0_ENTRY core_callback
define fun_WDF_INTERRUPT_ENABLE core_callback
define fun_WDF_DEVICE_D0_ENTRY_POST_INTERRUPTS_ENABLED core_callback
define fun_WDF_DMA_ENABLER_FILL core_callback
define fun_WDF_DMA_ENABLER_ENABLE core_callback
define fun_WDF_DMA_ENABLER_SELFMANAGED_IO_START core_callback
define fun_WDF_CHILD_LIST_SCAN_FOR_CHILDREN core_callback
define fun_WDF_DEVICE_DISARM_WAKE_FROM_S0 core_callback
define fun_WDF_DEVICE_DISARM_WAKE_FROM_SX core_callback
define fun_WDF_EVT_IO_RESUME core_callback
define fun_WDF_DEVICE_SELF_MANAGED_IO_INIT core_callback
define fun_WDF_DEVICE_SELF_MANAGED_IO_RESTART core_callback
define fun_WDF_DEVICE_DISABLE_WAKE_AT_BUS core_callback*/
